// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_chat_openai from "./routes/api/chat-openai.ts";
import * as $api_chat from "./routes/api/chat.ts";
import * as $index from "./routes/index.tsx";
import * as $ChatArea from "./islands/ChatArea.tsx";
import * as $DocumentPreview from "./islands/DocumentPreview.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/chat-openai.ts": $api_chat_openai,
    "./routes/api/chat.ts": $api_chat,
    "./routes/api/test-job-url.ts": $api_test_job_url,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ChatArea.tsx": $ChatArea,
    "./islands/DocumentPreview.tsx": $DocumentPreview,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
